setwd('D:/git/lyz05/北理珠/R/myworkspace')
#install.packages("RODBC")
library(xlsx)
library(RODBC)
input <- read.table("BMItables.txt",header = TRUE)
input
input <- read.xlsx("BMItables.xlsx",sheetName = "BMI",header = TRUE,encoding = "UTF-8")
input
con<-odbcConnect("mysqlodbc64",uid="root",pwd="5137",DBMSencoding="utf-8")
data <- sqlFetch(con,"BMI")
data$BMI <- data$体重/((data$身高/100)**2)
data
close(con)
write.table(data,file="BMItables1.txt",row.names = FALSE,col.names = FALSE,quote = FALSE)
png("BMItables.png")
plot(x=data$序号,y=data$BMI,xlim = c(1,5),xlab = "学生序号",ylab = "BMI",main = "学生BMI指数分布",xaxt="n")
axis(1,at=data$序号,labels = data$姓名,cex.axis=1)
dev.off()
jpeg("BMItables.jpg")
plot(x=data$序号,y=data$BMI,xlim = c(1,5),xlab = "学生序号",ylab = "BMI",main = "学生BMI指数分布",xaxt="n")
axis(1,at=data$序号,labels = data$姓名,cex.axis=1)
dev.off()
pdf("BMItables.pdf",family="GB1")
plot(x=data$序号,y=data$BMI,xlim = c(1,5),xlab = "学生序号",ylab = "BMI",main = "学生BMI指数分布",xaxt="n")
axis(1,at=data$序号,labels = data$姓名,cex.axis=1)
dev.off()