# Generated by Django 3.1.7 on 2021-05-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2021-05-12', max_length=20, verbose_name='出生日期'),
        ),
    ]
