# Generated by Django 3.1.7 on 2021-05-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0003_auto_20210512_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2021-05-26', max_length=20, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.IntegerField(choices=[(3, '未通过'), (2, '通过'), (1, '未审')], default=1, verbose_name='面试成绩'),
        ),
    ]
