# Generated by Django 3.1.7 on 2021-06-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0004_auto_20210526_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2021-06-02', max_length=20, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.IntegerField(choices=[(1, '未审'), (2, '通过'), (3, '未通过')], default=1, verbose_name='面试成绩'),
        ),
    ]
