url<-"D:\\git\\lyz05\\北理珠\\R"
setwd(url) 
detach(mtcars)
attach(mtcars)
png("relation.png")
plot(wt, mpg, main="汽车重量与耗油之间的关系", xlab="车重（千磅）", ylab="油耗", pch=19)
abline(lm(mpg~wt), col="black", lwd=2, lty=1)
lines(lowess(wt,mpg), col="blue", lwd=2, lty=2)
#install.packages("car")
dev.off()
png("Scatterdiagram.png")
library(car)
scatterplot(mpg ~ wt | cyl, data=mtcars, lwd=2, main="散点图", xlab="车重（千磅）", ylab="油耗（英里/加仑）", legend=TRUE)
dev.off()