# Generated by Django 3.1.7 on 2021-04-01 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=20)),
                ('press', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('publishdate', models.DateField()),
                ('shopnum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('readerno', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('readername', models.CharField(max_length=8)),
                ('sex', models.CharField(max_length=2)),
                ('identitycard', models.CharField(max_length=18)),
                ('workunit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ViewBook',
            fields=[
                ('bookno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=20)),
                ('press', models.CharField(max_length=30)),
                ('publishdate', models.DateField()),
                ('shopnum', models.IntegerField()),
                ('curnum', models.IntegerField()),
            ],
            options={
                'db_table': 'ViewBook',
            },
        ),
        migrations.CreateModel(
            name='ViewBorrow',
            fields=[
                ('readerno', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('readername', models.CharField(max_length=8)),
                ('bookno', models.CharField(max_length=10)),
                ('bookname', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=20)),
                ('press', models.CharField(max_length=30)),
                ('borrowdate', models.DateField()),
                ('shoulddate', models.DateField()),
                ('returndate', models.DateField(null=True)),
            ],
            options={
                'db_table': 'ViewBorrow',
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowdate', models.DateField()),
                ('shoulddate', models.DateField()),
                ('returndate', models.DateField(null=True)),
                ('bookno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('readerno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reader')),
            ],
        ),
    ]
