# Generated by Django 3.1.7 on 2021-04-07 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutApp', '0002_auto_20210407_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimg',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImg',
        ),
    ]
